
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_NUM = 17;
  public static final int TK_LCROCHET = 12;
  public static final int TK_TIMES = 6;
  public static final int TK_ADD = 4;
  public static final int TK_SEP = 2;
  public static final int TK_ELSE = 20;
  public static final int TK_WHILE = 24;
  public static final int TK_CORP_START = 22;
  public static final int TK_THEN = 21;
  public static final int TK_LPARENT = 10;
  public static final int TK_VAR_DECLARE = 14;
  public static final int TK_RPARENT = 11;
  public static final int TK_RCROCHET = 13;
  public static final int TK_VAR = 15;
  public static final int EOF = 0;
  public static final int TK_MOD = 8;
  public static final int error = 1;
  public static final int TK_IN = 18;
  public static final int TK_CORP_END = 23;
  public static final int TK_DIVIDE = 7;
  public static final int TK_ICNST = 16;
  public static final int TK_MINUS = 5;
  public static final int TK_IF = 19;
  public static final int TK_PRINT = 3;
  public static final int TK_ASSIGN = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_SEP",
  "TK_PRINT",
  "TK_ADD",
  "TK_MINUS",
  "TK_TIMES",
  "TK_DIVIDE",
  "TK_MOD",
  "TK_ASSIGN",
  "TK_LPARENT",
  "TK_RPARENT",
  "TK_LCROCHET",
  "TK_RCROCHET",
  "TK_VAR_DECLARE",
  "TK_VAR",
  "TK_ICNST",
  "TK_NUM",
  "TK_IN",
  "TK_IF",
  "TK_ELSE",
  "TK_THEN",
  "TK_CORP_START",
  "TK_CORP_END",
  "TK_WHILE"
  };
}

